# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "…/"

[hg_branch]
disabled = false
