format = """
$username\
$hostname\
$directory\
$git_branch\
$character"""

right_format = ""
add_newline = false

[username]
show_always = false # SSH接続時のみ表示
style_user = "bold white"
format = "[$user]($style) "

[hostname]
ssh_only = true # SSH接続時のみ表示
format = "@[$hostname]($style) "
style = "bold yellow"

[directory]
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 1 # パスを短縮表示 (e.g. /u/s/bin)
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"
truncation_length = 40

[character]
success_symbol = "[λ](bold green)" # 任意のシンボルに変更可
error_symbol = "[λ](bold red)"

[package]
disabled = true
[nodejs]
disabled = true
[rust]
disabled = true
[python]
disabled = true
